development:
  adapter: postgresql
  database: epm
  pool: 5
  password:

test:
  adapter: <%= ENV['db_adapter'] %>
  database: <%= ENV['db_name'] %>
  host: <%= ENV['db_host'] %>

production:
  adapter: <%= ENV['db_adapter'] %>
  database: <%= ENV['db_name'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
  host: <%= ENV['db_host'] %>